test:
  adapter: mysql2
  database: "vmail_test"
  mail_root: 'db/mail_root'

development:
  adapter: mysql2
  database: "vmail_development"
  mail_root: 'db/mail_root'

production:
  adapter: mysql2
  database: vmail
  strict: true
  mail_root: '/srv/mail'
